config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :tweets do
    resources :likes
  end

  get 'tweet/new'
  get 'users/:id', to: 'users#show', as: 'user_profile'
  get 'api/news', to: 'tweets#api'
  post 'tweets/retweet', to: 'tweets#retweet', as: 'retweet'
  post 'friends', to: "friends#create", as: 'friends'
  delete 'friends/:id', to: 'friends#destroy', as: 'delete_friend'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tweets#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
belongs_to :user

    def tweets_for_me
        for_me = (friend.friend_id == current_user.id)  
    end
end

app/models/like.rb
class Like < ApplicationRecord
belongs_to :tweet  
belongs_to :user

def img_like
    user_like = tweet.likes.find{ |like| like.user_id == tweet.likes.user.id_tweet}
end

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :contents, presence: true
    belongs_to :user
    has_many :likes, dependent: :destroy

    def retweets_for_me
        Tweet.where(original_tweet_id: self.id, retweeted: true)
    end
    def is_retweet?

        if self.retweeted == true && self.original_tweet_id.present?
            true
        else 
            false
        end 
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :likes 
  has_many :friends
  scope :tweets_for_me, ->(friends_ids) { Tweet.where(user_id: friends_ids) }

  # def tweets_for_me(friends)
  #   filtro = Hash.new
  #   friends.each do |f|
  #     if current_user.id = f.friends_id 
  #       filtro.push(f.friend_id)
  #     end
  #     return filtro
  #   end
  # end

  def is_friend_with(user)
    Friend.where(user_id: self.id, friend_id: user.id).present? 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :img_user])
        devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :img_user])

    end
end 

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    def create
        @friend = Friend.new
        @friend_user = User.find(params[:friend_id])
        @friend.friend_id = @friend_user.id #poner el id de usuario friend
        @friend.user_id = current_user.id

        if @friend.save
            flash[:alert] = "Se agrego exitosamente como amigo"
            redirect_to user_profile_path(@friend_user)
          else
            flash[:alert] = "Algo paso, intentalo de nuevo"
            redirect_to user_profile_path(@friend_user)
          end
    end

    def destroy
        @friend_user = User.find(params[:id])
        @friend = Friend.where(user_id: current_user.id, friend_id: params[:id]).first
        if @friend.destroy
            flash[:alert] = 'El amigo fue borrado con exito.'
            redirect_to user_profile_path(@friend_user)
        else
            flash[:alert] = 'algo paso, intentalo de nuevo'
            redirect_to user_profile_path(@friend_user)
        end
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_tweet
    before_action :find_like, only: [:destroy]
    def index

    end
  
    def show
  
    end
  
    def new
    end
  
    def create
      if already_liked?
        flash[:alert] = "Puedes dar like solo una vez"
      else
        @tweet.likes.create(user_id: current_user.id)
      end
      redirect_to root_path(@tweet)
    end
  
    def edit
    end
  
    def update
    end
  
    def destroy
      if !(already_liked?)
        flash[:alert] = "No puedes sacar el like"
      else
        @like.destroy
      end
      redirect_to root_path(@tweet)
    end

    private 
    def find_tweet
      @tweet = Tweet.find(params[:tweet_id])
      
    end

    def find_like
      @like = @tweet.likes.find(params[:id])
    end
   
    def already_liked?
      Like.where(user_id: current_user.id, tweet_id:
      params[:tweet_id]).exists?
    end
    
  end
  

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :set_tweet, only: %i[ show destroy ]

  def index
    if current_user
      @friends_ids = current_user.friends.pluck(:id)
      @friends_ids << current_user.id 
      @tweets = User.tweets_for_me(@friends_ids).order(created_at: :desc).page(params[:page]).per(50)
    else
      @tweets =Tweet.all.order(created_at: :desc).page(params[:page]).per(50)
    end
  end

  def show
    @users = User.all

  end

  def new
    @tweet = Tweet.new
  end

  def create 
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id if current_user
    #flag para saber si es retweet o no
    retweet_q = params[:tweet][:retweeted]
    tweet_id = params[:tweet][:id] 
    
    if retweet_q
      original_tweet_contents = Tweet.find(tweet_id).contents
      @tweet.retweeted = true
      @tweet.original_tweet_id = tweet_id
      @tweet.contents = original_tweet_contents
    end
    
    if @tweet.save
      flash[:alert] = "Se creo exitosamente"
      redirect_to root_path
    else
      flash[:alert] = "Algo paso, intentalo de nuevo"
      render 'new'
    end
  end
  
  # def edit
  # end

  # def update
  #     respond_to do |format|
  #         if @tweet.update(tweet_params)
  #           format.html { redirect_to @tweet, notice: "el tweet fue modificado" }
  #           format.json { render :show, status: :ok, location: @tweet }
  #         else
  #           format.html { render :edit, status: :unprocessable_entity }
  #           format.json { render json: @tweet.errors, status: :unprocessable_entity }
  #         end
  #       end
  # end

  def destroy
      @tweet = Tweet.find(params[:id])
      if @tweet.destroy
          flash[:alert] = 'El tweet fue borrado con exito.'
          redirect_to tweets_url
      else
          flash[:alert] = 'algo paso, intentalo de nuevo'
          redirect_to tweets_url
      end
  end

  def api
    @tweets = Tweet.all
    render json: @tweets.to_json(only: [:id, :contents])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  # def retweet_params
  #   params.require(:retweet).permit(:retweet_id, :content).merge(user_id: current_user.id)
  # end
  def tweet_params
    params.require(:tweet).permit(:contents, :id_user, :tweet_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/2e7e1bb83a.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary p-4">
    <div>
      <% if user_signed_in? %>
        <%= link_to "logout", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-lg" %>
        <span class="text-white font-weight-bold p-2" style="font-size: 27px;" >Bienvenido <%= current_user.user_name %>!</span>
      <% else %>
        <%= link_to "login", new_user_session_path, class: "btn btn-success btn-lg" %>
        <%= link_to "register", new_user_registration_path, class: "btn btn-warning btn-lg" %>
      <% end %>
    </div>
  
  </nav>


      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1 class="text-center">Tweeter</h1>
<div class="container p-5 ">
<%= link_to 'Crear un nuevo Tweet', new_tweet_path, class:"btn btn-primary pl-6 ml-5" if user_signed_in? %>
</div>
<div class="container p-5 mb-2 bg-light text-dark">
<%= paginate @tweets %>
    <% @tweets.each do |tweet| %>
    <div class="media rounded border border-info m-4">
      <img class="m-3 rounded border border-info" src="<%= tweet.user.img_user %> " alt="image_user" style="weigth: 70px; height: 70px;">
      <div class="media-body">
        <h5 class="m-2"><%=link_to tweet.user.user_name, user_profile_path(id: tweet.user.id) %></h5>
        <p class=""><%= tweet.contents %></p>
        <h5><%= link_to "Tweeted #{time_ago_in_words(tweet.created_at)} ago ", tweet %></h5>
<br>
        <% if tweet.user == current_user %>
        <div class="my-3">
        <span class="mx-2"><%= link_to 'eliminar', tweet,class:"btn btn-primary pl-6 ml-5", method: :delete, data: { confirm: 'Estas seguro?' } %></span>
        <span class="mx-2"><%= tweet.likes.count %><%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%></span>
        <% end %>
        <span>Retweets:<%= tweet.retweets_for_me.count %> </span>
        <span class="mx-2">
          <%= form_with(model: tweet, url: tweets_path, method: :post) do |form| %>
           <%=form.hidden_field :retweeted, value: true %>
           <%= form.hidden_field :id %>
           <%= form.submit 'Retweet', class:"btn btn-primary pl-6 ml-5"%>
           <%# <%= link_to 'Retweet', new_tweet_path, class:"btn btn-primary pl-6 ml-5" if user_signed_in? %> 
          <% end %>
        </span>
        </div>
      </div>
    </div>
    <% end %>
<span><%= paginate @tweets %></span>
    
</div>

app/views/tweets/new.html.erb
    <div class="container">
<div class="row p-5 mb-2 bg-light text-dark">
  <div class="col-4 offset-4">
      <h1>Que estas pensando, <%= current_user.user_name %>??</h1>
      <%= form_with(model: @tweet, local: true) do |form| %>
      <%= form.text_area :contents, size: "60x10" %>
      <span>
      <%= form.submit 'crear tweet', class:"btn btn-primary"%>
      </span>
      <% end %>
    </div>
  </div>
      <%= link_to 'volver al incio',root_path , class:"btn btn-primary ml-4" %>
</div>

app/views/tweets/show.html.erb
<div class="row p-5 mb-2 bg-light text-dark">
<div class="col-4 offset-4">
<h3>Detalles del Tweet</h3>
<% pre_like = @tweet.likes.find{ |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= link_to raw('<i class="fas fa-heart fa-3x" style="color: #ea2c62 ;"></i>'), tweet_like_path(@tweet, pre_like), method: :delete, class:"m-3" %>
<% else %>
  <%= link_to raw('<i class="far fa-heart fa-3x" style="color: #aaaaaa ;"></i>'), tweet_likes_path(@tweet), method: :post, class:"m-3" %>
<% end %>
<%= link_to raw('<i class="fas fa-share fa-3x""></i>'), retweet_path(@tweet), method: :post %>
<br>
<% @users.each do |u|%>
        <%  if @tweet.likes.find{ |like| like.user_id == u.id}%>
        <img src=" <%= u.img_user %> " alt="image_user" style="weigth: 70px; height: 70px;" class="m-3"><br>
        <% end %>
<% end %>
<%= link_to 'volver a inicio', retweet_path, class:"btn btn-primary" %>
</div>

</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>skdhfuisdfoijd</h1>
<div class="container p-5 ">
    <img class="m-3 rounded border border-info" src="<%= @user.img_user %> " alt="image_user" style="weigth: 70px; height: 70px;">
    <% if @user == current_user%>
        
    <% elsif current_user.is_friend_with(@user) == true%>
        <span class="mx-2"><%= link_to 'Eliminar de amigos', delete_friend_path(id: @user.id), method: :delete, class:"btn btn-primary pl-6 ml-5" %></span>
    <% else %>
        <span class="mx-2"><%= link_to 'Agregar amigo', friends_path(friend_id: @user.id), method: :post, class:"btn btn-primary pl-6 ml-5" %></span>
    <% end %>
</div>
<%= link_to 'volver al incio',root_path , class:"btn btn-primary ml-4" %>